node {
    stage('Preparation') {
        // Get some code from a GitHub repository
        git branch: 'master', credentialsId: 'b9ce2f10-b129-4323-aedc-1ba507a50952', url: 'https://github.com/harishnagandla1/war-web-project.git'
    }
    stage('Build') {
       env.PATH = "C:/Program Files/Maven/apache-maven-3.9.7/bin;c:\\Windows\\System32"
       bat 'mvn clean package'
    }
    stage('Archive') {
        archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
    }

    stage('Deploay') {
        deploy adapters: [tomcat9(credentialsId: 'MyTomCat', path: '', url: 'http://192.168.29.110:9999/')], contextPath: 'wwa', war: '**/*.jar'
    }

    stage('Notification') {
     emailext body: '''Hi Team,

           $DEFAULT_CONTENT

       This Jenkins Job related to Test Calculator Application Automation Test with TestNg Automation Framework, Maven build management and Java Project. Please find results of Jenkins Job build.

       Note: Please Don\'t reply to this mail, It is autogenerated.

       Thanks & Regards,
       Jenkins''', subject: '$DEFAULT_SUBJECT', to: 'harishnagandla1@gmail.com'
    }

}